name: Semgrep
run-name: Semgrep

#on: 
#  workflow_dispatch:
#  # IS_PRIMARY_UPDATE will be '' when the push comes from `update.yml` and 
#  # '#' when it comes from a job that needs it like `analyze-with-database`
#  push:
#    paths:
#      - '.github/workflows/semgrep.yml'

jobs:
  analyze:
    permissions:
      actions: read
      contents: read
      security-events: write

    uses: bughalla/bughalla/.github/workflows/__bughalla_semgrep.yml@main
    secrets: inherit